version: "3.7"

services:
  acj.duchack.cloud:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: acj.duchack.cloud
    restart: always
    ports:
      - 90:80
    networks:
      - npm
      - acj.duchack.cloud

networks:
  acj.duchack.cloud:
    name: acj.duchack.cloud
    driver: bridge
  npm:
    external: true